version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3-amd64
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    volumes:
      - "es_data:/home/marukawa/elk-work/data"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.9.3
    volumes:
      - "./pipeline:/usr/share/logstash/pipeline"
      - "./monthly:/var/log/monthly"
    depends_on:
      - elasticsearch

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - "./data/nginx/log:/var/log/nginx"
#    depends_on:
#      - logstash

volumes:
  es_data:
    driver: local
